
use_frameworks!
platform:ios, '10.0'
inhibit_all_warnings!

target 'HHProgressHUD_Example' do
  pod 'HHProgressHUD', :path => '../'
  pod 'SwiftEntryKit'
  target 'HHProgressHUDTests' do
    inherit! :search_paths

    
  end
end
