use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'HHProgressHUD' do
  pod 'HHProgressHUD', :path => '../'
  pod 'SwiftEntryKit', '~> 1.2.3'
  target 'HHProgressHUDTests' do
    inherit! :search_paths

    
  end
end
